import type { ITheme } from "@xterm/xterm";

export type TerminalThemeId =
  | "auto"
  | "dark"
  | "light"
  | "dracula"
  | "one-dark"
  | "monokai"
  | "solarized-dark"
  | "solarized-light"
  | "nord"
  | "github-dark"
  | "catppuccin-mocha"
  | "catppuccin-latte";

/** A named xterm.js theme bundled with the terminal package. */
export interface TerminalTheme {
  id: TerminalThemeId;
  name: string;
  isDark: boolean;
  palette: ITheme;
  /** CSS color or gradient string for the swatch background preview */
  swatchBg: string;
  /** Two accent sample colors for the swatch preview */
  swatchAccents: [string, string];
}

const TRANSPARENT = "rgba(0, 0, 0, 0)";

export const TERMINAL_THEMES: TerminalTheme[] = [
  {
    id: "auto",
    name: "Auto",
    isDark: false,
    palette: {},
    swatchBg: "linear-gradient(135deg, #18181b 50%, #f8fafc 50%)",
    swatchAccents: ["#3b82f6", "#1d4ed8"],
  },
  {
    id: "dark",
    name: "Dark",
    isDark: true,
    palette: {
      background: TRANSPARENT,
      foreground: "#e4e4e7",
      cursor: "#a1a1aa",
      cursorAccent: "#09090b",
      selectionBackground: "#3f3f46",
      black: "#18181b",
      red: "#ef4444",
      green: "#22c55e",
      yellow: "#eab308",
      blue: "#3b82f6",
      magenta: "#a855f7",
      cyan: "#06b6d4",
      white: "#e4e4e7",
      brightBlack: "#71717a",
      brightRed: "#f87171",
      brightGreen: "#4ade80",
      brightYellow: "#facc15",
      brightBlue: "#60a5fa",
      brightMagenta: "#c084fc",
      brightCyan: "#22d3ee",
      brightWhite: "#fafafa",
    },
    swatchBg: "#18181b",
    swatchAccents: ["#3b82f6", "#22c55e"],
  },
  {
    id: "light",
    name: "Light",
    isDark: false,
    palette: {
      background: TRANSPARENT,
      foreground: "#1e293b",
      cursor: "#475569",
      cursorAccent: "#f8fafc",
      selectionBackground: "rgba(148, 163, 184, 0.35)",
      black: "#334155",
      red: "#dc2626",
      green: "#16a34a",
      yellow: "#b45309",
      blue: "#1d4ed8",
      magenta: "#7c3aed",
      cyan: "#0e7490",
      white: "#cbd5e1",
      brightBlack: "#64748b",
      brightRed: "#ef4444",
      brightGreen: "#22c55e",
      brightYellow: "#d97706",
      brightBlue: "#3b82f6",
      brightMagenta: "#8b5cf6",
      brightCyan: "#06b6d4",
      brightWhite: "#f1f5f9",
    },
    swatchBg: "#f8fafc",
    swatchAccents: ["#1d4ed8", "#16a34a"],
  },
  {
    id: "dracula",
    name: "Dracula",
    isDark: true,
    palette: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
    swatchBg: "#282a36",
    swatchAccents: ["#bd93f9", "#50fa7b"],
  },
  {
    id: "one-dark",
    name: "One Dark",
    isDark: true,
    palette: {
      background: "#282c34",
      foreground: "#abb2bf",
      cursor: "#528bff",
      cursorAccent: "#282c34",
      selectionBackground: "#3e4451",
      black: "#3f4451",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#4f5666",
      brightRed: "#ff616e",
      brightGreen: "#a5e075",
      brightYellow: "#f0a45d",
      brightBlue: "#4dc4ff",
      brightMagenta: "#de73ff",
      brightCyan: "#4cd1e0",
      brightWhite: "#e6efff",
    },
    swatchBg: "#282c34",
    swatchAccents: ["#61afef", "#98c379"],
  },
  {
    id: "monokai",
    name: "Monokai",
    isDark: true,
    palette: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#f8f8f0",
      cursorAccent: "#272822",
      selectionBackground: "#49483e",
      black: "#272822",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#f4bf75",
      blue: "#66d9e8",
      magenta: "#ae81ff",
      cyan: "#a1efe4",
      white: "#f8f8f2",
      brightBlack: "#75715e",
      brightRed: "#f92672",
      brightGreen: "#a6e22e",
      brightYellow: "#f4bf75",
      brightBlue: "#66d9e8",
      brightMagenta: "#ae81ff",
      brightCyan: "#a1efe4",
      brightWhite: "#f9f8f5",
    },
    swatchBg: "#272822",
    swatchAccents: ["#f92672", "#a6e22e"],
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    isDark: true,
    palette: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#839496",
      cursorAccent: "#002b36",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
    swatchBg: "#002b36",
    swatchAccents: ["#268bd2", "#859900"],
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    isDark: false,
    palette: {
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#586e75",
      cursorAccent: "#fdf6e3",
      selectionBackground: "#eee8d5",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
    swatchBg: "#fdf6e3",
    swatchAccents: ["#268bd2", "#859900"],
  },
  {
    id: "nord",
    name: "Nord",
    isDark: true,
    palette: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      cursorAccent: "#2e3440",
      selectionBackground: "#434c5e",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
    swatchBg: "#2e3440",
    swatchAccents: ["#81a1c1", "#a3be8c"],
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    isDark: true,
    palette: {
      background: "#0d1117",
      foreground: "#c9d1d9",
      cursor: "#c9d1d9",
      cursorAccent: "#0d1117",
      selectionBackground: "#264f78",
      black: "#484f58",
      red: "#ff7b72",
      green: "#3fb950",
      yellow: "#d29922",
      blue: "#58a6ff",
      magenta: "#bc8cff",
      cyan: "#39c5cf",
      white: "#b1bac4",
      brightBlack: "#6e7681",
      brightRed: "#ffa198",
      brightGreen: "#56d364",
      brightYellow: "#e3b341",
      brightBlue: "#79c0ff",
      brightMagenta: "#d2a8ff",
      brightCyan: "#56d4dd",
      brightWhite: "#ecf2f8",
    },
    swatchBg: "#0d1117",
    swatchAccents: ["#58a6ff", "#3fb950"],
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    isDark: true,
    palette: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#585b70",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
    swatchBg: "#1e1e2e",
    swatchAccents: ["#89b4fa", "#a6e3a1"],
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    isDark: false,
    palette: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      cursorAccent: "#eff1f5",
      selectionBackground: "#acb0be",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
    swatchBg: "#eff1f5",
    swatchAccents: ["#1e66f5", "#40a02b"],
  },
];

/** Resolve the actual xterm.js ITheme for the given terminal theme ID + current app theme. */
export function getTerminalTheme(
  terminalThemeId: TerminalThemeId,
  appTheme: "dark" | "light",
): ITheme {
  if (terminalThemeId === "auto") {
    const fallback = TERMINAL_THEMES.find(
      (t) => t.id === (appTheme === "dark" ? "dark" : "light"),
    );
    return fallback?.palette ?? {};
  }
  const def = TERMINAL_THEMES.find((t) => t.id === terminalThemeId);
  return def?.palette ?? {};
}
